#!/bin/bash

set -euo pipefail

export DOTFILES_PATH="$HOME/.dotfiles"

git --version
git clone --depth 1 git@github.com:hminguezm/dotfiles.git "$DOTFILES_PATH"

source "$DOTFILES_PATH/scripts/install.sh"
