alias ga.="git add ."
alias gc="git commit"
alias gcb="git checkout -b"
alias gs="git status -sb"
alias gf="git fetch --all -p"
alias gpf="git push -f"
alias gpl="git pull --rebase --autostash"
alias gb="git branch"
